#!/usr/bin/env python3
"""Build the PDF half of the Braxby Cycles sample corpus.

Every PDF in ``corpus/pdf/`` is generated by this script. The PDFs are
committed, so you do not need to run this to use the corpus — but the source of
every word in them is here, which matters for one file in particular: the
workshop price list is a page of pixels with no text layer, and this script is
the only place its content exists as text.

Three of the seven files are deliberately hostile to text extraction. They are
not badly made by accident:

* ``catalogue-2026-brakes-spread.pdf`` writes its two columns one *row* at a
  time, left cell then right cell, so any extractor that reads in content-stream
  order or sorts by (y, x) interleaves the two columns into nonsense.
* ``compatibility-2026.pdf`` draws a table cell by cell with no delimiters, so
  the extracted text loses every column boundary.
* ``workshop-price-list-2026.pdf`` renders its text to a raster image and embeds
  that, with no text drawn on the page at all. A text extractor returns nothing.

The remaining four are ordinary, well-behaved single-column documents, so that
the corpus is not uniformly awkward.

Output is byte-stable: ``rl_config.invariant`` fixes the PDF creation date and
document ID, and the raster page is generated from a seeded RNG. Re-running this
script on an unchanged source produces identical files.

Requirements: reportlab and Pillow.

    python3 -m venv .venv
    .venv/bin/pip install reportlab pillow
    .venv/bin/python corpus/tools/build_pdfs.py
"""

from __future__ import annotations

import random
from pathlib import Path

from reportlab import rl_config

# Byte-stable output. Must be set before anything else in reportlab is used.
rl_config.invariant = 1

from PIL import Image, ImageDraw, ImageFont  # noqa: E402
from reportlab.lib.pagesizes import A4  # noqa: E402
from reportlab.lib.styles import ParagraphStyle  # noqa: E402
from reportlab.lib.units import mm  # noqa: E402
from reportlab.pdfbase import pdfmetrics  # noqa: E402
from reportlab.pdfgen import canvas as pdfcanvas  # noqa: E402
from reportlab.platypus import (  # noqa: E402
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
)

OUT_DIR = Path(__file__).resolve().parent.parent / "pdf"

PAGE_W, PAGE_H = A4
MARGIN = 22 * mm

BODY = ParagraphStyle(
    "body",
    fontName="Times-Roman",
    fontSize=10.5,
    leading=14.5,
    spaceAfter=7,
)
H1 = ParagraphStyle(
    "h1",
    fontName="Times-Bold",
    fontSize=16,
    leading=20,
    spaceAfter=12,
)
H2 = ParagraphStyle(
    "h2",
    fontName="Times-Bold",
    fontSize=11.5,
    leading=15,
    spaceBefore=10,
    spaceAfter=5,
)
META = ParagraphStyle(
    "meta",
    fontName="Times-Italic",
    fontSize=9,
    leading=12,
    spaceAfter=14,
)


# --------------------------------------------------------------------------
# Ordinary, well-behaved single-column documents
# --------------------------------------------------------------------------


def _footer(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("Times-Roman", 8)
    canvas.drawString(MARGIN, 12 * mm, doc.footer_left)
    canvas.drawRightString(PAGE_W - MARGIN, 12 * mm, f"Page {doc.page}")
    canvas.restoreState()


def build_flowing(filename: str, title: str, footer_left: str, blocks) -> Path:
    """Write a normal single-column PDF from (style, text) blocks."""
    path = OUT_DIR / filename
    doc = BaseDocTemplate(
        str(path),
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=MARGIN,
        title=title,
        author="Braxby Cycles Ltd",
        subject=title,
        creator="Braxby Cycles document system",
    )
    doc.footer_left = footer_left
    frame = Frame(
        MARGIN,
        MARGIN,
        PAGE_W - 2 * MARGIN,
        PAGE_H - 2 * MARGIN,
        id="body",
        showBoundary=0,
    )
    doc.addPageTemplates([PageTemplate(id="all", frames=[frame], onPage=_footer)])
    story = []
    for style, text in blocks:
        if style is None:
            story.append(Spacer(1, text))
        else:
            story.append(Paragraph(text, style))
    doc.build(story)
    return path


# --------------------------------------------------------------------------
# Trap 1: the two-column page written one row at a time
# --------------------------------------------------------------------------


def wrap(text: str, font: str, size: float, width: float) -> list[str]:
    """Greedy word wrap against real glyph widths."""
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if pdfmetrics.stringWidth(candidate, font, size) <= width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def build_two_column() -> Path:
    """A two-column page whose content stream runs across the columns.

    Each visual line is emitted as: left-column cell, then right-column cell, at
    the same y. Every extractor we know of — whether it reads the content stream
    in order or sorts text runs by (y, x) — therefore returns the two columns
    interleaved. That is the failure chapter 3 shows.
    """
    path = OUT_DIR / "catalogue-2026-brakes-spread.pdf"
    c = pdfcanvas.Canvas(str(path), pagesize=A4)
    c.setTitle("Braxby Cycles 2026 range guide - brakes")
    c.setAuthor("Braxby Cycles Ltd")
    c.setSubject("Range guide extract, brakes")

    col_w = (PAGE_W - 2 * MARGIN - 10 * mm) / 2
    left_x = MARGIN
    right_x = MARGIN + col_w + 10 * mm

    # Page furniture, drawn first and normally.
    c.setFont("Helvetica-Bold", 15)
    c.drawString(MARGIN, PAGE_H - MARGIN, "2026 range guide")
    c.setFont("Helvetica", 11)
    c.drawString(MARGIN, PAGE_H - MARGIN - 16, "Brakes - hydraulic disc calipers")
    c.setLineWidth(0.6)
    c.line(MARGIN, PAGE_H - MARGIN - 24, PAGE_W - MARGIN, PAGE_H - MARGIN - 24)

    left_heading = "Halvard R4 four-piston caliper"
    right_heading = "Halvard R2 two-piston caliper"

    left_text = (
        "The R4 is the four-piston caliper in the Halvard range and the one to "
        "fit if you are heavy on the brakes, ride loaded, or spend descents "
        "dragging a lever. Against the two-piston R2 it gives more pad area and "
        "a longer service life, at the cost of weight and a slightly firmer "
        "initial bite. The body is a two-piece forging with a bridge across the "
        "pistons, which is what keeps the flex out of it under load. Pistons are "
        "phenolic rather than alloy, so less heat is carried into the fluid on a "
        "long descent. The R4 is supplied with sintered pads as standard. "
        "Sintered pads take longer to bed in, are noisier in the wet for the "
        "first few rides, and last roughly twice as long as organic. Mount is "
        "post mount, front or rear, and the caliper takes the Halvard "
        "four-piston pad shape. Fitting a larger rotor than the frame mount is "
        "cut for needs the correct adapter for the position, and front and rear "
        "adapters are not interchangeable. Hose fitting is the current Halvard "
        "standard. It is not compatible with the 2019 R2 body without a new "
        "olive and insert, which is the single most common cause of a leak that "
        "appears a week after the job."
    )
    right_text = (
        "The R2 is the two-piston caliper and it is the right choice for most "
        "road bikes, most commuters, and any rider who is not routinely braking "
        "from speed with luggage on. It is lighter than the R4, it has a lighter "
        "lever feel, and it costs less to run because the pads are smaller. The "
        "body is a single-piece forging. Pistons are phenolic and the same fluid "
        "is used across the range, so a workshop only ever stocks one bleed kit. "
        "The R2 is supplied with organic pads as standard. Organic pads bed in "
        "within a few stops, are quieter, and wear faster, which is a trade most "
        "road riders take without noticing they have taken it. Mount is post "
        "mount, front or rear. The 2019 R2 body used a different hose fitting "
        "and is now superseded; a 2019 caliper being replaced needs a new olive "
        "and insert rather than a straight swap of the caliper. Adapters for the "
        "R2 have their own part numbers and several of them have been superseded "
        "in favour of the universal adapter, which ships with both bolt lengths "
        "rather than one."
    )

    font, size, leading = "Helvetica", 9.2, 12.4
    left_lines = wrap(left_text, font, size, col_w)
    right_lines = wrap(right_text, font, size, col_w)

    y = PAGE_H - MARGIN - 44

    # Headings, also emitted row-major: left heading then right heading.
    c.setFont("Helvetica-Bold", 10.5)
    c.drawString(left_x, y, left_heading)
    c.drawString(right_x, y, right_heading)
    y -= 16

    c.setFont(font, size)
    for i in range(max(len(left_lines), len(right_lines))):
        if i < len(left_lines):
            c.drawString(left_x, y, left_lines[i])
        if i < len(right_lines):
            c.drawString(right_x, y, right_lines[i])
        y -= leading

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(
        MARGIN,
        18 * mm,
        "Braxby Cycles Ltd - 2026 range guide - prices on the product page",
    )
    c.drawRightString(PAGE_W - MARGIN, 18 * mm, "Page 14")
    c.showPage()
    c.save()
    return path


# --------------------------------------------------------------------------
# Trap 2: a table drawn cell by cell, with one very long row
# --------------------------------------------------------------------------


def build_table() -> Path:
    """A compatibility table drawn as positioned cells with no delimiters."""
    path = OUT_DIR / "compatibility-2026.pdf"
    c = pdfcanvas.Canvas(str(path), pagesize=A4)
    c.setTitle("Braxby Cycles rotor and adapter compatibility 2026")
    c.setAuthor("Braxby Cycles Ltd")
    c.setSubject("Rotor and adapter compatibility")

    c.setFont("Helvetica-Bold", 15)
    c.drawString(MARGIN, PAGE_H - MARGIN, "Rotor and adapter compatibility")
    c.setFont("Helvetica", 10)
    c.drawString(MARGIN, PAGE_H - MARGIN - 15, "Halvard calipers, 2026 catalogue")

    intro = (
        "Read the row for the caliper you are fitting and the position it is "
        "going in. Front and rear adapters are not interchangeable, and an "
        "adapter that bolts up is not the same as an adapter with the right "
        "offset. Where the note column says to see a workshop bulletin, the "
        "bulletin is binding and this table is a summary."
    )
    y = PAGE_H - MARGIN - 34
    c.setFont("Helvetica", 9.4)
    for line in wrap(intro, "Helvetica", 9.4, PAGE_W - 2 * MARGIN):
        c.drawString(MARGIN, y, line)
        y -= 12.6

    headers = [
        "Caliper",
        "Position",
        "Frame mount",
        "Rotor",
        "Adapter",
        "Bolt",
        "Note",
    ]
    # Column x positions, in points from the left edge of the page.
    xs = [MARGIN, MARGIN + 78, MARGIN + 132, MARGIN + 210, MARGIN + 250, MARGIN + 316, MARGIN + 348]
    rows = [
        ["BRK-2200 R4", "front", "post 160 mm", "160 mm", "none", "22 mm", "direct fit"],
        ["BRK-2200 R4", "front", "post 160 mm", "180 mm", "ADP-3308", "30 mm", "universal adapter"],
        ["BRK-2200 R4", "front", "flat mount", "160 mm", "ADP-3308", "30 mm", "check fork clearance"],
        [
            "BRK-2200 R4",
            "rear",
            "post 160 mm",
            "180 mm",
            "see bulletin",
            "30 mm",
            "offset differs from front; see workshop bulletin 2026-04 before ordering an adapter",
        ],
        ["BRK-2204 R2", "front", "post 160 mm", "160 mm", "none", "22 mm", "direct fit"],
        ["BRK-2204 R2", "front", "post 160 mm", "180 mm", "ADP-3308", "30 mm", "BRK-1174 superseded"],
        ["BRK-2204 R2", "rear", "post 140 mm", "160 mm", "none", "22 mm", "BRK-1188 discontinued"],
        ["BRK-2190 R2", "front", "post 160 mm", "180 mm", "ADP-3308", "30 mm", "2019 body, new olive needed"],
    ]

    y -= 8
    c.setFont("Helvetica-Bold", 9)
    # Header cells, one drawString per cell, left to right.
    for x, header in zip(xs, headers):
        c.drawString(x, y, header)
    y -= 4
    c.setLineWidth(0.5)
    c.line(MARGIN, y, PAGE_W - MARGIN, y)
    y -= 12

    c.setFont("Helvetica", 8.6)
    for row in rows:
        # The long note in row 4 wraps; the wrapped remainder is drawn on its
        # own line under the note column, which is exactly what strands it from
        # its row once the page is linearised.
        note_lines = wrap(row[-1], "Helvetica", 8.6, PAGE_W - MARGIN - xs[-1])
        for x, cell in zip(xs, row[:-1]):
            c.drawString(x, y, cell)
        c.drawString(xs[-1], y, note_lines[0])
        y -= 11.4
        for extra in note_lines[1:]:
            c.drawString(xs[-1], y, extra)
            y -= 11.4
        y -= 2.4

    y -= 6
    c.setFont("Helvetica-Oblique", 8.6)
    tail = (
        "Rotor thickness is 1.8 mm new across the range and 1.5 mm at the wear "
        "limit. Bolt lengths above are the lengths supplied with the adapter, "
        "not the caliper bolts."
    )
    for line in wrap(tail, "Helvetica-Oblique", 8.6, PAGE_W - 2 * MARGIN):
        c.drawString(MARGIN, y, line)
        y -= 11.4

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(MARGIN, 18 * mm, "Braxby Cycles Ltd - technical reference - 2026")
    c.drawRightString(PAGE_W - MARGIN, 18 * mm, "Page 1")
    c.showPage()
    c.save()
    return path


# --------------------------------------------------------------------------
# Trap 3: a page of pixels with no text layer
# --------------------------------------------------------------------------

PRICE_LIST_LINES = [
    ("title", "BRAXBY CYCLES"),
    ("title", "MANCHESTER WORKSHOP"),
    ("head", "Price list, valid from 1 February 2026"),
    ("gap", ""),
    ("head", "Labour"),
    ("row", "Standard labour rate, per hour|58.00"),
    ("row", "Diagnostic half hour, credited against the job|29.00"),
    ("gap", ""),
    ("head", "Fixed-price jobs"),
    ("row", "Safety check|30.00"),
    ("row", "Full service|110.00"),
    ("row", "Full service with drivetrain deep clean|145.00"),
    ("row", "Hydraulic brake bleed, per brake|28.00"),
    ("row", "Gear set-up, front and rear|24.00"),
    ("row", "Headset service|45.00"),
    ("row", "Bottom bracket service|40.00"),
    ("row", "Wheel true and tension, per wheel|22.00"),
    ("row", "Wheel build, per wheel, excluding parts|55.00"),
    ("row", "Tubeless set-up, per wheel|18.00"),
    ("row", "Bike box packing for travel|65.00"),
    ("gap", ""),
    ("head", "Storage"),
    ("row", "Per day after fourteen days from the completion call|4.00"),
    ("gap", ""),
    ("note", "All prices in pounds sterling and include VAT."),
    ("note", "Parts are charged separately at the price on the product page."),
    ("note", "Labour is not discounted and is not included in promotional codes."),
    ("note", "Quotations are issued in writing before work begins."),
]


def _load_font(size: int):
    """A scalable font, without depending on any particular system font file."""
    candidates = [
        "/System/Library/Fonts/Supplemental/Courier New.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
    ]
    for candidate in candidates:
        if Path(candidate).exists():
            try:
                return ImageFont.truetype(candidate, size)
            except OSError:
                pass
    # Pillow 10.1+ ships a scalable fallback.
    return ImageFont.load_default(size=size)


def build_scanned() -> Path:
    """Render the price list to a raster image and embed it with no text layer.

    This is the only place in the corpus where these prices exist inside a
    document. A text extractor returns an empty string for this file, and every
    question in questions.jsonl marked ``requires_ocr`` is unanswerable until an
    OCR step is added to the pipeline. That is the point of the file.
    """
    path = OUT_DIR / "workshop-price-list-2026.pdf"
    png_path = OUT_DIR / "workshop-price-list-2026.page1.png"

    scale = 2  # ~144 dpi against A4
    w, h = int(595 * scale), int(842 * scale)
    img = Image.new("L", (w, h), 244)
    draw = ImageDraw.Draw(img)

    f_title = _load_font(int(19 * scale))
    f_head = _load_font(int(13 * scale))
    f_row = _load_font(int(11 * scale))
    f_note = _load_font(int(9 * scale))

    left = int(60 * scale)
    right = w - int(60 * scale)
    y = int(70 * scale)

    for kind, text in PRICE_LIST_LINES:
        if kind == "gap":
            y += int(12 * scale)
            continue
        if kind == "title":
            draw.text((left, y), text, font=f_title, fill=25)
            y += int(26 * scale)
        elif kind == "head":
            draw.text((left, y), text, font=f_head, fill=30)
            y += int(6 * scale)
            draw.line([(left, y + int(9 * scale)), (right, y + int(9 * scale))], fill=90, width=max(1, scale // 2))
            y += int(20 * scale)
        elif kind == "row":
            label, price = text.split("|")
            draw.text((left, y), label, font=f_row, fill=35)
            price_text = f"GBP {price}"
            bbox = draw.textbbox((0, 0), price_text, font=f_row)
            draw.text((right - (bbox[2] - bbox[0]), y), price_text, font=f_row, fill=35)
            y += int(17 * scale)
        elif kind == "note":
            draw.text((left, y), text, font=f_note, fill=60)
            y += int(13 * scale)

    # Make it look photocopied: seeded noise, a slight skew, and a dirty edge.
    rng = random.Random(20260201)
    pixels = img.load()
    for _ in range(w * h // 260):
        x = rng.randrange(w)
        yy = rng.randrange(h)
        pixels[x, yy] = max(0, pixels[x, yy] - rng.randrange(30, 150))
    img = img.rotate(0.45, resample=Image.BICUBIC, fillcolor=244, expand=False)
    edge = ImageDraw.Draw(img)
    edge.rectangle([0, 0, w - 1, h - 1], outline=190, width=max(2, scale))
    img = img.convert("L")
    img.save(png_path, optimize=True)

    c = pdfcanvas.Canvas(str(path), pagesize=A4)
    c.setTitle("Braxby Cycles workshop price list 2026 (scanned)")
    c.setAuthor("Braxby Cycles Ltd")
    c.setSubject("Workshop price list, scanned from paper")
    # No drawString anywhere on this page. The image is the whole page.
    c.drawImage(str(png_path), 0, 0, width=PAGE_W, height=PAGE_H)
    c.showPage()
    c.save()
    png_path.unlink()
    return path


# --------------------------------------------------------------------------
# Document text
# --------------------------------------------------------------------------

TERMS_OF_SALE = [
    (H1, "Braxby Cycles Ltd — terms and conditions of sale"),
    (META, "Version 6. In force from 1 January 2026. Supersedes version 5."),
    (H2, "1. About these terms"),
    (
        BODY,
        "1.1 These terms apply to every contract for the sale of goods and services "
        "between Braxby Cycles Ltd (\"we\", \"us\") and the customer (\"you\"), whether "
        "placed through www.braxbycycles.example, at the trade counter, or by email.",
    ),
    (
        BODY,
        "1.2 Nothing in these terms limits or excludes your statutory rights as a "
        "consumer. Where a term in this document is less favourable to you than a "
        "right you hold by statute, the statutory right applies and the term does "
        "not.",
    ),
    (
        BODY,
        "1.3 Where you are buying in the course of a business under a trade account, "
        "the trade account terms apply in addition to these terms, and where the two "
        "conflict the trade account terms prevail.",
    ),
    (H2, "2. Placing an order"),
    (
        BODY,
        "2.1 Your order is an offer to buy. No contract is formed when you place the "
        "order or when you receive the automatic acknowledgement. A contract is "
        "formed only when we send a dispatch confirmation, and only for the goods "
        "named in that confirmation.",
    ),
    (
        BODY,
        "2.2 We may decline an order without giving a reason. In practice we decline "
        "for three reasons: the item is out of stock, the price shown was wrong, or "
        "the delivery address is outside the territories in clause 4.1.",
    ),
    (
        BODY,
        "2.3 A special-order item is ordered in against your order and is identified "
        "as such on the product page before you buy. A special-order item cannot be "
        "cancelled once we have placed the order with our supplier.",
    ),
    (H2, "3. Prices and payment"),
    (
        BODY,
        "3.1 The price is the price shown on the product page at the moment the order "
        "is placed, and includes VAT where VAT applies. Delivery is charged in "
        "addition and is shown separately at checkout.",
    ),
    (
        BODY,
        "3.2 If the price shown was obviously wrong, and the error is one you could "
        "reasonably have recognised, we may cancel the order and refund you in full "
        "rather than supply at that price.",
    ),
    (
        BODY,
        "3.3 Payment is taken at the point of order. Where an order is held for the "
        "verification described in clause 4.6, payment is taken and refunded in full "
        "if the order is subsequently cancelled.",
    ),
    (
        BODY,
        "3.4 Workshop labour is charged at the rates on the workshop price list "
        "current on the date the job is booked in, and is quoted in writing before "
        "work begins.",
    ),
    (H2, "4. Delivery, risk and title"),
    (
        BODY,
        "4.1 We deliver to addresses in the United Kingdom, the Republic of Ireland "
        "and the European Union. We do not deliver outside those territories.",
    ),
    (
        BODY,
        "4.2 Delivery timescales are estimates and are not of the essence of the "
        "contract. Where delivery is materially delayed you may cancel the order and "
        "receive a full refund, including the delivery charge paid.",
    ),
    (
        BODY,
        "4.3 Risk in the goods passes to you on delivery to the address you gave, or "
        "on collection from our workshop.",
    ),
    (
        BODY,
        "4.4 Title in the goods passes to you when we have received payment in full.",
    ),
    (
        BODY,
        "4.5 Damage in transit must be notified within three working days of "
        "delivery. After that period the carrier will not accept a claim and the "
        "matter is dealt with under clause 6 instead.",
    ),
    (
        BODY,
        "4.6 Orders over £400 delivered to an address other than the billing address "
        "of the payment card are held for a verification call, which we make within "
        "one working day.",
    ),
    (H2, "5. Cancellation and returns"),
    (
        BODY,
        "5.1 The Customer may cancel and return any unused Goods within thirty (30) "
        "days of delivery and receive a refund in full. The Goods must be unfitted, "
        "in resaleable condition and in their original packaging.",
    ),
    (
        BODY,
        "5.2 The thirty day period runs from the date of delivery. Where a carrier "
        "has recorded a delivery date, that record is determinative.",
    ),
    (
        BODY,
        "5.3 The following are excluded from clause 5.1: goods cut to length; opened "
        "liquids including tubeless sealant; special-order items; gift vouchers; and "
        "goods returned without packaging that forms part of the saleable product.",
    ),
    (
        BODY,
        "5.4 We refund the outbound standard delivery charge where the whole order is "
        "returned. We do not refund any premium paid for an expedited service, and we "
        "do not refund the outbound charge on a partial return.",
    ),
    (
        BODY,
        "5.5 Refunds are made to the original payment method within five working days "
        "of the goods arriving at our returns unit.",
    ),
    (H2, "6. Faulty goods"),
    (
        BODY,
        "6.1 Goods that are faulty are dealt with under our warranty policy and not "
        "under clause 5. Carriage on a faulty return is at our cost in both "
        "directions, and the thirty day period in clause 5.1 does not apply.",
    ),
    (
        BODY,
        "6.2 Our warranty terms by product category, and the exclusions that apply to "
        "consumables, are set out in the warranty policy, which forms part of these "
        "terms.",
    ),
    (H2, "7. Our liability"),
    (
        BODY,
        "7.1 We do not exclude or limit our liability for death or personal injury "
        "caused by our negligence, for fraud, or for any liability that cannot be "
        "excluded by law.",
    ),
    (
        BODY,
        "7.2 Subject to clause 7.1, our total liability arising out of any one order "
        "is limited to the price paid for that order.",
    ),
    (
        BODY,
        "7.3 We are not liable for any loss arising from the fitting of goods by a "
        "third party, or from goods being used outside the manufacturer's stated "
        "limits.",
    ),
    (H2, "8. Events outside our control"),
    (
        BODY,
        "8.1 We are not liable for a failure to perform caused by an event outside "
        "our reasonable control, including carrier failure, industrial action, and "
        "the interruption of supply from a manufacturer.",
    ),
    (
        BODY,
        "8.2 Where such an event continues for more than thirty days, either party "
        "may cancel the affected order and we will refund any sum paid for it.",
    ),
    (H2, "9. Changes to these terms"),
    (
        BODY,
        "9.1 We may amend these terms. The version in force is the version published "
        "on the website at the moment your order is placed, and an amendment does not "
        "affect an order already accepted.",
    ),
    (H2, "10. Governing law"),
    (
        BODY,
        "10.1 These terms are governed by the law of England and Wales, and the "
        "courts of England and Wales have exclusive jurisdiction.",
    ),
    (
        BODY,
        "10.2 Nothing in clause 10.1 deprives a consumer resident in the Republic of "
        "Ireland or in a member state of the European Union of the protection of the "
        "mandatory rules of the law of their own country of residence.",
    ),
]

TRADE_TERMS = [
    (H1, "Trade account terms"),
    (META, "In force from 1 March 2026. Issued by Buying. Review due 1 March 2027."),
    (
        BODY,
        "These terms govern trade accounts. They sit alongside our terms and "
        "conditions of sale, and where the two conflict, these terms win. Where a "
        "trade account holder buys as a consumer, using a personal card and a "
        "personal address, the retail policies apply to that order instead.",
    ),
    (H2, "Opening an account"),
    (
        BODY,
        "Accounts are opened for businesses trading in the bicycle sector: shops, "
        "workshops, fleet operators, cycling clubs with a purchasing officer, and "
        "frame builders. We ask for two trade references and a bank reference, and "
        "we take four to six weeks to open an account. There is no fee.",
    ),
    (
        BODY,
        "An account is opened with a credit limit set by Buying. The limit is "
        "reviewed after six months and annually after that. Orders that would take "
        "the balance over the limit are held rather than declined, and Buying calls "
        "the account holder the same working day.",
    ),
    (H2, "Payment terms"),
    (
        BODY,
        "Thirty days from the date of invoice. Invoices are issued on dispatch, not "
        "on order. Statements are issued on the first working day of each month.",
    ),
    (
        BODY,
        "An account more than fourteen days overdue is placed on hold and no further "
        "orders are dispatched until the balance is cleared. We would rather make an "
        "awkward telephone call in week two than write off an invoice in month six, "
        "and we say so when the account is opened.",
    ),
    (H2, "Minimum order"),
    (
        BODY,
        "The minimum trade order is £250 excluding VAT and excluding delivery. Orders "
        "below the minimum are accepted at retail prices, and the system will say so "
        "before the order is confirmed rather than afterwards.",
    ),
    (H2, "Delivery"),
    (
        BODY,
        "Trade delivery is free on orders over £250 to a mainland UK address. Below "
        "that threshold, and to all other addresses, the retail delivery bands apply. "
        "Trade orders are picked in the same queue as retail orders, in payment "
        "order, with no priority in either direction.",
    ),
    (H2, "Returns and restocking"),
    (
        BODY,
        "Stock lines may be returned within thirty days, unused and in original "
        "packaging, with no restocking charge.",
    ),
    (
        BODY,
        "Non-stock items — anything ordered in specifically against a trade order — "
        "carry a restocking charge of 15 per cent of the trade price, deducted from "
        "the credit note. This is the charge our own supplier makes to us, passed on "
        "at cost and not marked up.",
    ),
    (
        BODY,
        "Special-order items and anything cut to length cannot be returned at all. "
        "The returns desk marks a trade return as stock or non-stock; the charge is "
        "applied by Finance against the account, never at the desk.",
    ),
    (H2, "Warranty"),
    (
        BODY,
        "Trade orders carry a twelve month warranty from the date of invoice, which "
        "replaces the retail terms in the warranty policy. The exclusions are the "
        "same: crash damage, fitting error, corrosion through neglect, modification, "
        "and consumables.",
    ),
    (
        BODY,
        "A trade account holder making a claim on behalf of their own customer deals "
        "with us, not with the end customer, and we will not correspond directly with "
        "an end customer on a trade warranty claim.",
    ),
    (H2, "Pricing"),
    (
        BODY,
        "Trade prices are published to the account and are not visible to retail "
        "customers. Trade pricing and the retail price promise do not combine: an "
        "account holder buying at trade cannot also claim a retail price match.",
    ),
    (
        BODY,
        "Prices are reviewed quarterly. Where a price rises we give thirty days' "
        "notice and honour the old price on any order already placed.",
    ),
    (H2, "Ending an account"),
    (
        BODY,
        "Either party may close an account on thirty days' written notice. We may "
        "close an account immediately where an invoice is more than sixty days "
        "overdue, where the account has been used to buy for resale outside the "
        "sector, or where a member of our staff has been abused.",
    ),
]

RECALL = [
    (H1, "Safety recall notice"),
    (META, "Issued 18 November 2025 by Braxby Cycles Ltd. Reference REC-2025-11."),
    (H2, "What is affected"),
    (
        BODY,
        "Emberly XR front hubs from the 2024 production batch, sold as part number "
        "WHL-5104 and inside complete Emberly XR wheelsets supplied between March "
        "2024 and October 2025.",
    ),
    (
        BODY,
        "Affected hubs carry a serial number etched on the non-drive side flange in "
        "the range EX-24 0001 to EX-24 4200 inclusive. Serials beginning EX-25 are "
        "not affected. The current part, WHL-5120, is not affected.",
    ),
    (H2, "The defect"),
    (
        BODY,
        "A batch of front hub shells was machined with an axle seat below the "
        "specified diameter. The bearing can develop play under load, and in a small "
        "number of cases the drive-side bearing has moved in the shell. The failure "
        "presents as a knock felt through the bars under braking, and as lateral "
        "play at the rim that does not respond to a bearing preload adjustment.",
    ),
    (
        BODY,
        "No injury has been reported. We are recalling on the basis of the failure "
        "mode rather than on the basis of harm, which is the right way round.",
    ),
    (H2, "What to do"),
    (
        BODY,
        "Stop riding the wheel. Do not attempt to repack or replace the bearings; a "
        "new bearing in an out-of-tolerance seat fails again, usually faster.",
    ),
    (
        BODY,
        "Email support@braxbycycles.example with the serial number and the order "
        "number if you have it. We will send a prepaid label. A replacement front "
        "wheel built on the current hub is sent as soon as the affected wheel is "
        "received, and there is no charge for anything, including the labour of "
        "moving your rotor and cassette across.",
    ),
    (
        BODY,
        "Where the wheel was supplied inside a complete bike built by our workshop, "
        "book the bike in instead and we will do the swap on the stand.",
    ),
    (H2, "If you bought the wheel second hand"),
    (
        BODY,
        "The recall follows the hub, not the purchaser. Send the serial number and we "
        "will replace it whether or not you were the original buyer and whether or "
        "not you have any proof of purchase.",
    ),
    (H2, "Deadline"),
    (
        BODY,
        "There is no deadline. This notice stays open until the last affected hub is "
        "returned or the last of them has worn out on a shelf somewhere.",
    ),
]

WHEELBUILD = [
    (H1, "Workshop standard: wheel building"),
    (META, "WKS-STD-002. Issued by the Manchester workshop, 15 January 2026."),
    (
        BODY,
        "This standard applies to every wheel laced, tensioned or re-tensioned in the "
        "Manchester workshop, whether the parts were bought from us or supplied by "
        "the customer. A wheel built to this standard is a workshop-built assembly "
        "and carries the warranty term the warranty policy gives that category.",
    ),
    (H2, "Before lacing"),
    (
        BODY,
        "Check the rim for a manufacturer's maximum tension figure and write it on "
        "the job sheet. Where the rim gives a figure, that figure is the ceiling and "
        "it overrides everything below. Where the rim gives no figure, use the "
        "targets in this standard.",
    ),
    (
        BODY,
        "Check the hub flange for damage, check the freehub for play, and measure the "
        "hub before cutting or ordering spokes. Do not trust a published "
        "specification for a hub that has been serviced by somebody else.",
    ),
    (
        BODY,
        "Spokes are measured, not estimated. A spoke that is one millimetre short "
        "will hold tension and will fail at the elbow within a season.",
    ),
    (H2, "Tension targets"),
    (
        BODY,
        "Rear drive side: 110 to 125 kgf. Rear non-drive side: whatever the dish "
        "requires, typically 50 to 60 per cent of the drive side. Front disc, "
        "non-drive side: 100 to 115 kgf. Front disc, drive side: as the dish "
        "requires.",
    ),
    (
        BODY,
        "Tension variation around the wheel must be within plus or minus 10 per cent "
        "on the higher-tension side. A wheel that meets its average and fails its "
        "variation is not a finished wheel.",
    ),
    (H2, "Truing tolerances"),
    (
        BODY,
        "Lateral: 0.3 mm or better. Radial: 0.4 mm or better. Dish: 0.5 mm or better, "
        "measured with the dishing gauge and confirmed by flipping the wheel in the "
        "stand rather than by trusting the stand's own centring.",
    ),
    (H2, "Stress relieving"),
    (
        BODY,
        "Stress relieve at every tension step, not once at the end. The wheel is not "
        "finished until it makes no noise when relieved and the tension has not moved "
        "afterwards. A wheel that pings on its first ride was signed off early.",
    ),
    (H2, "Finishing and handover"),
    (
        BODY,
        "Record on the job sheet: the rim, the hub, the spoke length used, the final "
        "average tension on each side, and the measured dish. This record is what a "
        "warranty decision is made from up to three years later, so write it for a "
        "stranger.",
    ),
    (
        BODY,
        "Tell the customer that the wheel comes back at 300 km for a first "
        "re-tension, book it there and then if they are willing, and write on the "
        "job sheet that they were told. Spokes bed in, and the first re-tension is "
        "the difference between a wheel that stays true and one that does not.",
    ),
    (H2, "Customer-supplied parts"),
    (
        BODY,
        "We will build on a customer-supplied rim and hub at the mechanic's "
        "discretion. We will not build with second-hand spokes under any "
        "circumstances. Where the customer supplied any part of the build, the "
        "twelve-month labour guarantee does not apply, and the job sheet must say so "
        "before the wheel is started.",
    ),
]

SUPPLIER_ONBOARDING = [
    (H1, "Supplier onboarding checklist"),
    (META, "BUY-CHK-003. Issued by Buying, 1 February 2026."),
    (
        BODY,
        "Every new supplier goes through this list before a first purchase order is "
        "raised. It exists because two suppliers in the last five years shipped "
        "against terms nobody had read, and both times the argument was about "
        "something on this page.",
    ),
    (H2, "Commercial"),
    (
        BODY,
        "Agree cost prices in writing, in pounds sterling, with the currency stated "
        "even when it is obvious. Agree payment terms, minimum order value, and "
        "whether carriage is included above a threshold. Agree what happens to a "
        "price when the underlying currency moves, because it will.",
    ),
    (
        BODY,
        "Ask for the returns and warranty position in writing before the first order: "
        "how long, what is excluded, who pays the carriage, and whether a faulty part "
        "is credited or replaced. A supplier who will not put this in writing is "
        "telling you something.",
    ),
    (H2, "Product data"),
    (
        BODY,
        "We need, for every line: the manufacturer's part number, a description, the "
        "packed weight in grams, the packed dimensions, the barcode, and the country "
        "of origin. The weight is the one that gets forgotten and it is the one that "
        "prices delivery, so a line without a weight does not go live.",
    ),
    (
        BODY,
        "Photographs at 2000 pixels on the long edge, on white, with no watermark. "
        "Line drawings where the part has a fit dimension that matters.",
    ),
    (H2, "Technical"),
    (
        BODY,
        "Fit standards, torque figures, and any approved-use list — the hookless rim "
        "and tyre approval lists are the current example, and the workshop needs them "
        "before the first unit is sold, not after the first complaint.",
    ),
    (
        BODY,
        "Spares availability, stated as a number of years, and the part numbers of "
        "the spares. A component we cannot get bearings for in three years is a "
        "component we should not range.",
    ),
    (H2, "Compliance and logistics"),
    (
        BODY,
        "Confirm whether any line is classed as dangerous goods. Sealant, aerosols "
        "and pressurised cartridges are, and they change what we can ship and where.",
    ),
    (
        BODY,
        "Confirm lead times honestly and record them. A lead time we have written "
        "down is a lead time we can quote to a customer; a lead time somebody "
        "remembers from a phone call is not.",
    ),
    (H2, "Sign-off"),
    (
        BODY,
        "Buying signs off the commercial section, the workshop manager signs off the "
        "technical section, and Fulfilment signs off product data and logistics. All "
        "three, before the first purchase order. There is no fast track and asking "
        "for one is how both of the arguments above started.",
    ),
]


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = [
        build_flowing(
            "terms-of-sale-2026.pdf",
            "Braxby Cycles Ltd - terms and conditions of sale",
            "Braxby Cycles Ltd - terms and conditions of sale - version 6",
            TERMS_OF_SALE,
        ),
        build_flowing(
            "trade-account-terms-2026.pdf",
            "Braxby Cycles Ltd - trade account terms",
            "Braxby Cycles Ltd - trade account terms - March 2026",
            TRADE_TERMS,
        ),
        build_flowing(
            "safety-recall-2025-11.pdf",
            "Braxby Cycles Ltd - safety recall REC-2025-11",
            "Braxby Cycles Ltd - safety recall REC-2025-11",
            RECALL,
        ),
        build_flowing(
            "wheelbuilding-standard-2026.pdf",
            "Braxby Cycles Ltd - workshop standard, wheel building",
            "Braxby Cycles Ltd - WKS-STD-002 - wheel building",
            WHEELBUILD,
        ),
        build_flowing(
            "supplier-onboarding-checklist-2026.pdf",
            "Braxby Cycles Ltd - supplier onboarding checklist",
            "Braxby Cycles Ltd - BUY-CHK-003 - supplier onboarding",
            SUPPLIER_ONBOARDING,
        ),
        build_two_column(),
        build_table(),
        build_scanned(),
    ]
    for path in sorted(written):
        print(f"wrote {path.relative_to(OUT_DIR.parent)}  ({path.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
